// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApYGZ1jkHexA-mgV-eWLchrBN95Up5LEU',
    appId: '1:541677356493:web:4123bcff215f4185ba3084',
    messagingSenderId: '541677356493',
    projectId: 'waiter-app-a50c1',
    authDomain: 'waiter-app-a50c1.firebaseapp.com',
    storageBucket: 'waiter-app-a50c1.firebasestorage.app',
    measurementId: 'G-HVDS8D8N51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt40_7veibdfpGyDZcZ_anfRetRMVNpcI',
    appId: '1:541677356493:android:71b068c44166cfc8ba3084',
    messagingSenderId: '541677356493',
    projectId: 'waiter-app-a50c1',
    storageBucket: 'waiter-app-a50c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GST3COZZgQstuymWWhoh01HvkXv6Atw',
    appId: '1:541677356493:ios:6830ec0d510ba757ba3084',
    messagingSenderId: '541677356493',
    projectId: 'waiter-app-a50c1',
    storageBucket: 'waiter-app-a50c1.firebasestorage.app',
    iosBundleId: 'com.example.demodidong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8GST3COZZgQstuymWWhoh01HvkXv6Atw',
    appId: '1:541677356493:ios:6830ec0d510ba757ba3084',
    messagingSenderId: '541677356493',
    projectId: 'waiter-app-a50c1',
    storageBucket: 'waiter-app-a50c1.firebasestorage.app',
    iosBundleId: 'com.example.demodidong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApYGZ1jkHexA-mgV-eWLchrBN95Up5LEU',
    appId: '1:541677356493:web:633393c04166d281ba3084',
    messagingSenderId: '541677356493',
    projectId: 'waiter-app-a50c1',
    authDomain: 'waiter-app-a50c1.firebaseapp.com',
    storageBucket: 'waiter-app-a50c1.firebasestorage.app',
    measurementId: 'G-V7K1PYG7LW',
  );
}
